version: "3"
services:
  urjcShare:
    image: davidtb10/urjcshare:latest
    restart: always
    ports:
      - "8443:8443"
    networks:
      - urjcShare-network
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    restart: on-failure
    ports:
      - "5000:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=pass--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - urjcShare-network
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=urjc_share  

networks:
  urjcShare-network: 
