version: "3"
services:
  urjcShare:
    image: crusasul/urjcshare:latest
    restart: always
    ports:
      - "8443:8443"
    networks:
      - urjcShare-network
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/urjc_share?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=pass
 
  mysqldb:
    image: mysql:8
    restart: on-failure
    ports:
      - "5000:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=pass--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - urjcShare-network
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=urjc_share
      - MYSQL_USER=root  

networks:
  urjcShare-network: 
